---
configRev: 3
sources:
    LONGMYND:
        binpath: /home/pi/longmynd/longmynd
        mediapath: /home/pi/lmmedia
        statuspath: /home/pi/lmstatus
        tstimeout: 5000

bands:
    None:
        source: LONGMYND
        lofreq: 0
        loside: SUM
        pol:  NONE
        port: BOTTOM
        gpioid: 1
    LNB Low: &bandlnblow
        source: LONGMYND
        lofreq: 9750000
        loside: LOW
        pol:  HORIZONTAL
        port: TOP
        gpioid: 0

presets:
    QO-100 Beacon: &presetdefault
        freq: 10491500
        sr:   1500
        band: *bandlnblow

    QO-100 Scan:
        freq:
          - 10497750
          - 10498250
          - 10498750
          - 10499250
        sr:
          - 250
          - 333
          - 500
        band: *bandlnblow

default: *presetdefault

ir:
    repeatFirst: 200
    repeatDelay: 100
    repeatReset: 400
    libraryPath: /home/pi/rydeplayer
    handsets:
        - handset.sample

gpio:
    repeatFirst: 200
    repeatDelay: 100
    rxGood: 4
    buttons:
        POWER:  16
        UP:     14
        DOWN:   27
        LEFT:   22
        RIGHT:  23
        SELECT: 24
        BACK:   25
        MENU:   5
        MUTE:   6
    switches:
        highgoing:
            OSDON: 26
        lowgoing:
            OSDOFF: 26

osd:
    timers:
        USERTRIGGER: 10
        PROGRAMTRIGGER: 10
    active:
        MUTE:
            datum: TR
            x: 0.03
            y: 0.3
            w: 0.3
            h: 0.3
        SIGLEVEL: null
        REPORT: null
        PROGRAM: null
        FREQ: null
        BW: null
    inactive:
        MUTE: null

network:
    bindaddr: 'localhost'
    port: 8765

shutdownBehavior: APPSTOP

debug:
    enableMenu: False
    autoplay: True
    disableHardwareCodec: True
