---
configRev: 3
playerID: "TEST CONFIG"
sources:
    LONGMYND:
        binpath: /home/pi/longmynd/longmynd
        mediapath: /home/pi/lmmedia
        statuspath: /home/pi/lmstatus
        tstimeout: 5000
    COMBITUNER:
        binpath: /home/pi/combituner/CombiTunerExpress
        mediapath: /home/pi/ctmedia

bands:
    None LM:
        source: LONGMYND
        lofreq: 0
        loside: SUM
        pol:  NONE
        port: BOTTOM
        gpioid: 1
    None CT: &bandnonect
        source: COMBITUNER
        lofreq: 0
        loside: SUM
        gpioid: 1
    LNB Low: &bandlnblow
        source: LONGMYND
        lofreq: 9750000
        loside: LOW
        pol:  HORIZONTAL
        port: TOP
        gpioid: 0
    BATC Streamer: &bandbatcstream
        source: RTMPSTREAM
        domain: rtmp.batc.org.uk
        rtmpapp: live
        networkTimeout: 5
        networkTimeoutInit: 25
        gpioid: 0

presets:
    QO-100 Beacon: &presetdefault
        freq: 10491500
        sr:   1500
        band: *bandlnblow

    QO-100 Scan:
        freq:
          - 10497750
          - 10498250
          - 10498750
          - 10499250
        sr:
          - 250
          - 333
          - 500
        band: *bandlnblow

    70cm CT:
        freq: 437000
        bw:   333
        band: *bandnonect

    QO-100 net stream:
        streamname: oscar100net
        band: *bandbatcstream

default: *presetdefault

ir:
    repeatFirst: 200
    repeatDelay: 100
    repeatReset: 400
    libraryPath: /home/pi/rydeplayer
    handsets:
        - handset.sample

gpio:
    repeatFirst: 200
    repeatDelay: 100
    rxGood: 4
    buttons:
        POWER:  16
        UP:     14
        DOWN:   27
        LEFT:   22
        RIGHT:  23
        SELECT: 24
        BACK:   25
        MENU:   5
        MUTE:   6
    switches:
        highgoing:
            OSDON: 26
        lowgoing:
            OSDOFF: 26
    band:
        - 12
        - 13
        - 15

osd:
    timers:
        USERTRIGGER: 10
        PROGRAMTRIGGER: 10
    active:
        PLAYERID: null
        MUTE:
            datum: TR
            x: 0.03
            y: 0.3
            w: 0.3
            h: 0.3
        VOLUME: null
        SIGLEVEL: null
        REPORT: null
        POWERLEVEL: null
        PROGRAM: null
        FREQ: null
        BW: null
    inactive:
        PLAYERID: null
        MUTE: null

network:
    bindaddr: 'localhost'
    port: 8765

watchdog:
    minRestartTime: 0.1
    maxRestartTime: 300
    backoffRate: 2

watchdogService:
    serviceInterval: 1
    pidPath: "/tmp/rydePlayer.pid"

shutdownBehavior: APPSTOP

audio:
    muteOnStartup: False
    volumeOnStartup: 100
    volumeStep: 25
    enableMenu: False

debug:
    enableMenu: False
    autoplay: True
    disableHardwareCodec: True
    useFTfont: False
